"""rename author_id to user_id

Revision ID: 6a5cb14cbecd
Revises: 
Create Date: 2026-02-25 11:41:07.646262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a5cb14cbecd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. RENAME column (This keeps your data!)
    op.alter_column('posts', 'author_id',
                    new_column_name='user_id',
                    existing_type=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'user_id')
    op.create_table('videos',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('raw_file_path', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('compressed_file_path', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('status', mysql.ENUM('PROCESSING', 'READY', 'FAILED'), nullable=False),
    sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_size', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('compressed_size', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('original_filename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('mime_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('error_message', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###