"""rename description to caption

Revision ID: a5e35b922aba
Revises: 549dc8697a5f
Create Date: 2026-02-26 11:23:57.381057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a5e35b922aba'
down_revision: Union[str, None] = '549dc8697a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('caption', sa.Text(), nullable=True))
    op.drop_column('posts', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('description', mysql.TEXT(), nullable=True))
    op.drop_column('posts', 'caption')
    # ### end Alembic commands ###